routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home',function(){
    return redirect('/');
});
Route::get('/','DirectoryController@home');
Route::post('/user-login','LoginController@authenticate');
Route::post('/user-login-main','LoginController@authenticateMain');

Route::get('auth/linkedin', 'LinkedinController@linkedinRedirect');
Route::get('auth/linkedin/callback', 'LinkedinController@linkedinCallback');

Route::middleware(['auth'])->group(function () {

    Route::get('/directory','DirectoryController@alumnis');
    Route::get('/directory/{id}','DirectoryController@alumni');

    Route::get('/my-profile','UserController@profile');
    Route::post('/my-profile','UserController@update');
    Route::post('/my-profile/update-photo','UserController@updatePhoto');
    Route::post('/my-profile/update-cover','UserController@updateCover');
    Route::post('/my-profile/update-resume','UserController@updateResume');
    Route::post('/my-profile/update-fields','UserController@updateFields');
    Route::post('/my-profile/update-location','UserController@updateLocation');

    Route::post('/my-profile/add-career','CareerController@add');
    Route::post('/my-profile/delete-career','CareerController@delete');
    Route::get('/my-profile/get-career/{id}','CareerController@get');
    Route::post('/my-profile/update-career','CareerController@update');

    Route::post('/my-profile/add-education','EducationController@add');
    Route::post('/my-profile/delete-education','EducationController@delete');
    Route::get('/my-profile/get-education/{id}','EducationController@get');
    Route::post('/my-profile/update-education','EducationController@update');

    Route::post('/my-profile/add-portfolio','PortfolioController@add');
    Route::post('/my-profile/delete-portfolio','PortfolioController@delete');
    Route::get('/my-profile/get-portfolio/{id}','PortfolioController@get');
    Route::post('/my-profile/update-portfolio','PortfolioController@update');

    Route::post('/my-profile/add-skills','UserController@addSkill');
    Route::post('/my-profile/delete-tag-skill','UserController@deleteSkill');
    Route::post('/my-profile/add-industry','UserController@addIndustry');
    Route::post('/my-profile/delete-tag-industry','UserController@deleteIndustry');

    Route::get('/my-profile/update-child/{value}','UserController@updateChild');

    Route::get('/add-event/{id}','UserController@addEvent');
    Route::get('/delete-event/{id}','UserController@deleteEvent');

    Route::get('/my-events','UserController@myEvents');
    Route::get('/my-jobs','UserController@myJobs');
    Route::get('/my-jobs/renew/{id}','UserController@myJobsRenew');

    Route::get('/create-job','UserJobController@create');
    Route::get('/edit-job/{id}','UserJobController@edit');
    Route::get('/delete-job/{id}','UserJobController@delete');
    Route::post('/store-job','UserJobController@store');
    Route::post('/update-job','UserJobController@update');
    Route::get('/see-applicants/{id}','UserJobController@applicants');
    Route::get('/apply-job/{id}','UserJobController@apply');
    Route::get('/cancel-apply-job/{id}','UserJobController@cancel');

    Route::get('/news-and-events','ArticleController@index');
    Route::get('/alumni-owned-businesses','ArticleController@businesses');
    Route::get('/article/{slug}','ArticleController@showNews');
    Route::get('/event/{slug}','ArticleController@showEvent');
    Route::post('/involvements/update','UserController@updateInvolvement');

    Route::get('/jobs','JobsController@index');
    Route::get('/jobs/{id}','JobsController@single');
    Route::get('/change-password',function(){ return view('change-password'); });
    Route::post('/change-password','UserController@updatePassword');
});

Route::get('admin/login', function () {
    return view('auth.login');
});

Route::group(['prefix' => 'admin','middleware' => 'admin'], function() {

    Route::get('/',function(){
        return redirect('admin/alumnis');
    });

    Route::group(['prefix' => 'alumnis','middleware' => 'auth'], function() {
        Route::get('/','AlumniController@index');
        Route::get('/unverified','AlumniController@unverified');
        Route::get('/new','AlumniController@newUsers');
        Route::get('/new-export','AlumniController@newUsersExport');
        Route::get('/create','AlumniController@create');
        Route::post('/store','AlumniController@store');
        Route::post('/update','AlumniController@update');
        Route::get('/delete/{id}','AlumniController@delete');
        Route::get('/deactivate/{id}','AlumniController@deactivate');
        Route::get('/activate/{id}','AlumniController@activate');
        Route::get('/verify/{id}','AlumniController@verify');
        Route::get('/{id}','AlumniController@edit');
    });

    Route::group(['prefix' => 'home-sliders','middleware' => 'auth'], function() {
        Route::get('/','HomesliderController@index');
        Route::get('/create','HomesliderController@create');
        Route::post('/store','HomesliderController@store');
        Route::post('/update','HomesliderController@update');
        Route::get('/delete/{id}','HomesliderController@delete');
        Route::get('/{id}','HomesliderController@edit');
    });

    Route::group(['prefix' => 'events','middleware' => 'auth'], function() {
        Route::get('/','EventController@index');
        Route::post('/store','EventController@store');
        Route::get('/create','EventController@create');
        Route::post('/update','EventController@update');
        Route::get('/month','EventController@month');
        Route::get('/attendees/{id}','EventController@attendees');
        Route::get('/attendees/delete/{id}/{user_id}','EventController@deleteAttendee');
        Route::get('/attendees/export/{id}','EventController@exportAttendees');
        Route::get('/delete/{id}','EventController@delete');
        Route::get('/{id}','EventController@edit');
    });

    Route::group(['prefix' => 'news','middleware' => 'auth'], function() {
        Route::get('/','NewsController@index');
        Route::post('/store','NewsController@store');
        Route::get('/create','NewsController@create');
        Route::post('/update','NewsController@update');
        Route::get('/delete/{id}','NewsController@delete');
        Route::get('/{id}','NewsController@edit');
    });

    Route::group(['prefix' => 'business','middleware' => 'auth'], function() {
        Route::get('/','BusinessController@index');
        Route::post('/store','BusinessController@store');
        Route::get('/create','BusinessController@create');
        Route::post('/update','BusinessController@update');
        Route::get('/delete/{id}','BusinessController@delete');
        Route::get('/{id}','BusinessController@edit');
    });

    Route::group(['prefix' => 'volunteers','middleware' => 'auth'], function() {
        Route::get('/','VolunteerController@index');
        Route::post('/store','VolunteerController@store');
        Route::get('/create','VolunteerController@create');
        Route::post('/update','VolunteerController@update');
        Route::get('/delete/{id}','VolunteerController@delete');
        Route::get('/{id}','VolunteerController@edit');
    });

    Route::group(['prefix' => 'jobs','middleware' => 'auth'], function() {
        Route::get('/','JobsController@adminIndex');
        Route::get('/email','JobsController@email');
        Route::post('/email/update','JobsController@emailUpdate');
        Route::post('/store','JobsController@store');
        Route::get('/create','JobsController@create');
        Route::post('/update','JobsController@update');
        Route::get('/delete/{id}','JobsController@delete');
        Route::get('/{id}','JobsController@edit');
    });

    Route::group(['prefix' => 'contacts','middleware' => 'auth'], function() {
        Route::get('/','ContactController@index');
        Route::get('/export','ContactController@export');
        Route::get('/view/{id}','ContactController@view');
        Route::get('/delete/{id}','ContactController@delete');
    });

    Route::group(['prefix' => 'settings','middleware' => 'auth'], function() {
        Route::group(['prefix' => 'home-items','middleware' => 'auth'], function() {
            Route::get('/','Admin\HomeItemController@index');
            Route::post('/store','Admin\HomeItemController@store');
            Route::get('/create','Admin\HomeItemController@create');
            Route::post('/update','Admin\HomeItemController@update');
            Route::get('/{id}','Admin\HomeItemController@edit');
            Route::get('/delete/{id}','Admin\HomeItemController@delete');
        });
    });

    Route::group(['prefix' => 'amsi-voices','middleware' => 'auth'], function() {
        Route::group(['prefix' => 'current','middleware' => 'auth'], function() {
            Route::get('/','AmsiVoiceController@current');
            Route::post('/store','AmsiVoiceController@storeCurrent');
            Route::get('/create','AmsiVoiceController@createCurrent');
            Route::post('/update','AmsiVoiceController@updateCurrent');
            Route::get('/{id}','AmsiVoiceController@editCurrent');
            Route::get('/delete/{id}','AmsiVoiceController@deleteCurrent');
        });
        Route::group(['prefix' => 'past','middleware' => 'auth'], function() {
            Route::get('/','AmsiVoiceController@past');
            Route::post('/store','AmsiVoiceController@storePast');
            Route::get('/create','AmsiVoiceController@createPast');

app/Models/Portfolio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Portfolio extends Model
{
    use HasFactory;

    protected $fillable = ['title','file_name','original_name','mime_type','path'];

    public function getUrlAttribute(){
        return asset('public/'.$this->path.'/'.$this->file_name);
    }
}

resources/views/admin/partials/pages/additional-content-form.blade.php
<div class="form-group" style="border-top: 3px solid #ccc;padding-top: 20px;">
    <label for="exampleTextareaa1">Additional Content (Top)</label>
    <div class="form-group">
    <input type="hidden" name="additional_content_top" value="{{ isset($page) ? $page->additional_content_top : '' }}">
    <div class="summernote">
        @if(isset($page))
            {!! $page->additional_content_top !!}
        @endif
    </div>
    </div>
    <br/>
    <br/>
    <label for="exampleTextareaa1">Additional Content (Bottom)</label>
    <div class="form-group">
        <input type="hidden" name="additional_content_bottom" value="{{ isset($page) ? $page->additional_content_bottom : '' }}">
        <div class="summernote">
            @if(isset($page))
                {!! $page->additional_content_bottom !!}
            @endif
        </div>
    </div>
    <br/>
    <br/>
    @if($forms)
        <label for="exampleTextareaa1">Add a form:</label>
        <select name="form_id" class="form-control">
            <option value="0">None</option>
            @foreach($forms as $id=>$form)
                <?php
                    $selectedFormId = 0;
                    if(isset($page)){
                        if($page->forms()->count()){
                            $selectedFormId = $page->forms()->first()->form->id;
                        }
                    }
                ?>
                <option {{ $selectedFormId==$form->id ? 'selected="selected"' : '' }} value="{{ $form->id }}">{{ $form->title }}</option>
            @endforeach
        </select>
    @endif
</div>

resources/views/admin/partials/pages/button-link.blade.php
<div class="form-group">
    <div class="row ">
        <div class="col-md-12">
            <strong>Addition Button/Link</strong>
            <br/>
            <br/>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>Text EN:</label>
                <input type="text" class="form-control" placeholder="Submit" name="buttonLink[title]" value="{{ $page->buttonLinks->title }}">
            </div>
            <div class="form-group">
                <label>Link  EN:</label>
                <input type="text" class="form-control" placeholder="mailto:info@sharjaharchicture.com" name="buttonLink[value]" value="{{ $page->buttonLinks->value }}">
            </div>
        </div>
        <div class="col-md-6 text-right">
            <div class="form-group">
                <label>Text AR:</label>
                <input type="text" class="form-control" placeholder="Submit" name="buttonLink[title_ar]" value="{{ $page->buttonLinksAr->title_ar }}">
            </div>
            <div class="form-group">
                <label>Link AR:</label>
                <input type="text" class="form-control" placeholder="mailto:info@sharjaharchicture.com" name="buttonLink[value_ar]" value="{{ $page->buttonLinksAr->value_ar }}">
            </div>
        </div>
    </div>
</div>

resources/views/admin/partials/pages/content-ar-form.blade.php
<h4 class="card-title">Arabic</h4>
<div class="form-group">
    <label for="exampleInputNamea1">Title</label>
    <input type="text" class="form-control" id="exampleInputNamea1" placeholder="Name" name="name_ar" required value="{{ isset($page) ? $page->name_ar : '' }}">
</div>
<div class="form-group">
    <label for="exampleInputEmaila3">Content</label>
    <input type="hidden" name="content_ar" value="{{ isset($page) ? $page->content_ar : '' }}"/>
    <div class="summernote">
        {!!  isset($page) ? $page->content_ar : '' !!}
    </div>
</div>

resources/views/admin/partials/pages/content-en-form.blade.php
<h4 class="card-title">English</h4>
<div class="form-group">
    <label for="exampleInputName1">Title</label>
    <input type="text" class="form-control" id="exampleInputName1" placeholder="Name" name="name" required value="{{ isset($page) ? $page->name : '' }}">
</div>
<div class="form-group">
    <label for="exampleInputEmail3">Content</label>
    <input type="hidden" name="content" value="{{ isset($page) ? $page->content : '' }}"/>
    <div class="summernote">
        {!! isset($page) ? $page->content : '' !!}
    </div>
</div>

resources/views/admin/partials/pages/featured-image-form.blade.php
<div class="form-group" style="border-top:3px solid #ccc" >
    <br/>
    <strong>Add a featured image</strong>
    <br/>
    <br/>
    <div class="row">
        <div class="col-md-12" id="file-uploads">
            <div class="file-upload card-box">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Square Image(1000x1000):</label>
                            <input type="file" class="form-control" name="images[1][square]" placeholder="Upload Image">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Landscape Image(1000x600):</label>
                            <input type="file" class="form-control" name="images[1][landscape]" placeholder="Upload Image">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Image Caption EN:</label>
                            <input type="text" class="form-control" placeholder="Image Caption EN" name="captions[1][EN]">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Image Caption AR:</label>
                            <input type="text" class="form-control" placeholder="Image Caption AR" name="captions[1][AR]">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <button class="form-control" id="add-file" type="button">Add more images</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/partials/pages/featured-images-list.blade.php
@if(count($page->sliders))
    <div class="form-group" style="border-top:3px solid #ccc">
    <br/>
    <strong>Featured Images</strong>
    <br/><br/>

        <div class="row" id="current-images">
            @foreach($page->sliders as $slide)
                <div class="file-upload">
                    <div class="row">
                        <div class="col-md-6">
                            @if($slide->landscape)
                                <img src="{{ asset('public'.$slide->landscape->url) }}" width="100%">
                                <br/>
                                <br/>
                            @endif
                            @if($slide->square)
                                <img src="{{ asset('public'.$slide->square->url) }}" width="100%">
                            @endif
                            <input type="hidden" name="uploads[{{$slide->landscape->id}}][id]" value="{{ $slide->landscape->id }}" width="100%">
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Image Caption EN:</label>
                                <input type="text" class="form-control" placeholder="Image Caption EN" name="upload-captions[{{$slide->landscape->id}}][EN]"  value="{{ $slide->landscape->caption }}">
                            </div>
                            <div class="form-group">
                                <label>Image Caption AR:</label>
                                <input type="text" class="form-control" placeholder="Image Caption AR" name="upload-captions[{{$slide->landscape->id}}][AR]"  value="{{ $slide->landscape->caption_ar }}">
                            </div>

                            @if($slide->square)
                                <div class="form-group">
                                    <label>Replace Square:</label>
                                    <input type="file" class="form-control" name="uploads[{{$slide->square->id}}]" placeholder="Upload Image">
                                </div>
                            @else
                                <div class="form-group">
                                    <label>Add Square:</label>
                                    <input type="hidden" name="newUploads[slide_id]" value="{{$slide->id}}">
                                    <input type="file" class="form-control" name="newUploads[square]" placeholder="Upload Image">
                                </div>
                            @endif

                            @if($slide->landscape)
                                <div class="form-group">
                                    <label>Replace Landscape:</label>
                                    <input type="file" class="form-control" name="uploads[{{$slide->landscape->id}}]" placeholder="Upload Image">
                                </div>
                            @else
                                <div class="form-group">
                                    <label>Add Landscape:</label>
                                    <input type="hidden" name="newUploads[slide_id]" value="{{$slide->id}}">
                                    <input type="file" class="form-control" name="newUploads[landscape]" placeholder="Upload Image">
                                </div>
                            @endif

                            <div class="form-group">
                                <label>Remove Slide:<input type="checkbox" class="form-control" name="delete[{{$slide->id}}]" placeholder="Upload Image" value="{{$slide->id}}"></label>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endif

resources/views/admin/partials/pages/parent-page-form.blade.php
<div class="form-group">
    <label for="exampleInputNamea1">Parent Page</label>
    <select class="form-control" name="page_id">
        <option value="0">None</option>
        @if(isset($pages))
            @foreach($pages as $select_page)
                <?php $selected = ''; ?>

                @if(isset($page))
                    @if($page->parent)
                        @if($select_page->id == $page->parent->id)
                            <?php $selected = "selected=selected"; ?>
                        @endif
                    @endif
                @endif

                <option {{ $selected }} value="{{ $select_page->id }}">{{ $select_page->name }}</option>
            @endforeach
        @endif
    </select>
</div>

resources/views/admin/partials/pages/status.blade.php
<div class="form-group">
    <label for="exampleInputNamea1">Page status</label>
    <select class="form-control" name="active">
        <option {{ $page->active==1 ? 'selected="selected"' : '' }} value="1">Active</option>
        <option {{ $page->active==0 ? 'selected="selected"' : '' }} value="0">Hidden</option>
    </select>
</div>

resources/views/admin/partials/pages/template-page-form.blade.php
<div class="form-group">
    <label for="exampleInputNamea1">Page Template</label>
    <select class="form-control" name="page_type">
        @if(isset($templates))
            @foreach($templates as $template)
                <?php $selected = ''; ?>

                @if(isset($page))
                    @if($template->slug == $page->page_type)
                        <?php $selected = "selected=selected"; ?>
                    @endif
                @endif

                <option {{ $selected }} value="{{ $template->slug }}">{{ $template->name }}</option>
            @endforeach
        @endif
    </select>
</div>